.DEFAULT_GOAL := help

.PHONY: help
help:
	@echo -e "Usage: \tmake [TARGET]\n"
	@echo -e "Targets:"
	@echo -e "  package            Creates a tar file with the required Python code"
	@echo -e "  publish            Publishes the Python package to PyPI"
	@echo -e "  clean              Remove Python autogenerated code"

.PHONY: package
package: clean
	@./scripts/package.sh

.PHONY: publish
publish:
	@./scripts/publish.sh

.PHONY: clean
clean:
	@rm -rf packages/python/buda/**/*pb2*.py
