.DEFAULT_GOAL := help

.PHONY: help
help:
	@echo -e "Usage: \tmake [TARGET]\n"
	@echo -e "Targets:"
	@echo -e "  package-python            Creates a tar file with the required Python code"
	@echo -e "  clean-python              Remove Python autogenerated code"

.PHONY: package-python
package-python: clean-python
	./scripts/package-python.sh

.PHONY: clean-python
clean-python:
	@rm -rf $(PYTHON_DIR)/buda/entities/*pb2*.py
	@rm -rf $(PYTHON_DIR)/buda/services/*pb2*.py
