#!/usr/bin/env bash

usage() { echo "Usage: $0 [-i <proto-input-dir>] [-o <output-dir>] [-c <command>]" 1>&2; exit 1; }

while getopts ":i:o:c:" a; do
    case "${a}" in
        i)
            i=${OPTARG}
            ;;
        o)
            o=${OPTARG}
            ;;
        c)
            c=${OPTARG}
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if [ -z "${i}" ] || [ -z "${o}" ] || [ -z "${c}" ] ; then
    usage
fi

docker run -it --rm -e COMMAND=${c} -v ${i}:/work/buda -v ${o}:/build bufferapp/budapest
